# Generated by Django 4.1 on 2022-08-22 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('b_title', models.CharField(max_length=300)),
                ('b_author', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(default=datetime.date(2022, 8, 22))),
            ],
        ),
    ]
