# Generated by Django 4.1 on 2022-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
