# Generated by Django 4.1 on 2022-09-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewset_api', '0004_remove_student_book_student_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewset_api.library'),
        ),
    ]
