# Generated by Django 4.1 on 2022-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixin_api', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_name',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
