# Generated by Django 4.1 on 2022-08-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
